# Generated by Django 5.1.5 on 2025-01-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0002_message_is_read_alter_message_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='content',
        ),
    ]
